name: Mike Katilius
favicon: null
layout_spectrum: 0.25387
typography_spectrum: 0.53491
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecdbc1'
    - '#fef3dd'
    - '#d6c0a9'
    - '#4e3f3a'
    - '#7a7977'
  brandStrength: 0.5
  lightness: 0.5339901787228882
  saturation: 1
  rhythmicContrast: 0.07822835305705667
purpose: []
