name: Mike Katilius
favicon: null
layout_spectrum: 0.384645314887166
typography_spectrum: 0.6376471784897149
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5984034189023077
  lightness: 0.5339901787228882
  saturation: 0.6075684695970267
  rhythmicContrast: 0.07822835305705667
purpose: []
