name: Mike Katilius
favicon: null
layout_spectrum: 0.384645314887166
typography_spectrum: 0.6376471784897149
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fce5f7'
    - '#cc4aaf'
    - '#ac168c'
    - '#f08cd9'
  brandStrength: 0.5
  lightness: 0.5339901787228882
  saturation: 0.6075684695970267
  rhythmicContrast: 0.07822835305705667
purpose: []
